package rolling

// creditFee leaves the transaction's actual fee on the stack. Shape and script
// checks are done by compileRollingCredit before this arithmetic is used.
func (b builder) creditFee() {
	b.AddInt64(0)
	for i := 1; i <= MaxMoneyInputs; i++ {
		b.AddOp(OP_INSPECTNUMINPUTS).AddInt64(int64(i)).AddOp(OP_GREATERTHAN).AddOp(OP_IF)
		b.inputValue(i)
		b.AddOp(OP_ADD).AddOp(OP_ENDIF)
	}
	b.AddOp(OP_INSPECTNUMINPUTS).AddInt64(1).AddOp(OP_GREATERTHAN).AddOp(OP_IF)
	b.outputValue(1)
	b.AddOp(OP_SUB).AddOp(OP_ENDIF)
}

func compileRollingCredit(p RollingParameters) ([]byte, error) {
	b := newBuilder()
	b.header(3, 1, MaxMoneyInputs+1)
	b.marker(p.ControllerID, 0)
	b.inputValue(0)
	b.eq(ControllerSats)
	b.outputValue(0)
	b.eq(ControllerSats)
	b.outputMatchesInput(0, 0)
	b.AddOp(OP_INSPECTNUMINPUTS).AddInt64(1).AddOp(OP_GREATERTHAN).AddOp(OP_IF)
	b.AddOp(OP_INSPECTNUMOUTPUTS)
	b.eq(4)
	b.outputMatchesInput(1, 0)
	b.outputValue(1)
	b.bounded(ControllerSats, maxMoney)
	b.AddOp(OP_DROP)
	b.AddOp(OP_ELSE).AddOp(OP_INSPECTNUMOUTPUTS)
	b.eq(3)
	b.AddOp(OP_ENDIF)
	for i := 1; i <= MaxMoneyInputs; i++ {
		b.AddOp(OP_INSPECTNUMINPUTS).AddInt64(int64(i)).AddOp(OP_GREATERTHAN).AddOp(OP_IF)
		b.inputScript(i)
		b.inputScript(0)
		b.AddOp(OP_EQUALVERIFY)
		b.inputValue(i)
		b.bounded(ControllerSats, maxMoney)
		b.AddOp(OP_DROP).AddOp(OP_ENDIF)
	}
	b.AddOp(OP_INSPECTNUMOUTPUTS).AddOp(OP_1SUB).AddOp(OP_INSPECTOUTPUTVALUE)
	b.eq(0)
	b.AddOp(OP_INSPECTNUMOUTPUTS).AddOp(OP_1SUB).AddOp(OP_INSPECTOUTPUTSCRIPTPUBKEY)
	b.eq(1)
	b.AddData([]byte{0x4e, 0x73}).AddOp(OP_EQUALVERIFY)
	b.AddOp(OP_INSPECTNUMOUTPUTS).AddInt64(2).AddOp(OP_SUB).AddOp(OP_INSPECTOUTPUTVALUE)
	b.eq(0)
	b.AddOp(OP_INSPECTNUMOUTPUTS).AddInt64(2).AddOp(OP_SUB).AddOp(OP_INSPECTOUTPUTSCRIPTPUBKEY)
	b.eq(-1)
	b.AddOp(OP_DROP)
	b.creditFee()
	b.bounded(0, p.FeeCap)
	b.feeRate(p.FeerateCap)
	b.AddOp(OP_0NOTEQUAL).AddOp(OP_IF)
	b.AddOp(OP_DEPTH)
	b.eq(2*HistoryWitnessItems + 2)
	b.AddOp(OP_ELSE).AddOp(OP_DEPTH)
	b.eq(HistoryWitnessItems + 2)
	b.AddOp(OP_ENDIF)
	b.AddOp(OP_SIZE)
	b.eq(ReceiptSize)
	domain := p.ReceiptDomain()
	b.AddOp(OP_DUP).AddInt64(32).AddOp(OP_LEFT).AddData(domain[:]).AddOp(OP_EQUALVERIFY).
		AddOp(OP_DUP).AddOp(OP_TOALTSTACK).AddOp(OP_SHA256).
		AddData(p.ReceiptKey[:]).AddOp(OP_CHECKSIGFROMSTACK).AddOp(OP_VERIFY)
	b.receiptField(84, 8)
	b.unsigned(8, 100_000_000_000)
	b.bounded(1, 100_000_000_000)
	b.AddInt64(WindowSeconds + 1).AddOp(OP_ADD).AddOp(OP_CHECKTIMEVERIFY)
	b.receiptField(32, 8)
	b.unsigned(8, int64(MaxSequence-1))
	b.rollingNumber(0, 12, int64(MaxSequence))
	b.AddOp(OP_LESSTHAN).AddOp(OP_VERIFY)
	b.receiptField(40, 8)
	b.unsigned(8, p.Budget)
	b.bounded(1, p.Budget)
	b.rollingNumber(0, 4, p.Budget)
	b.AddOp(OP_ADD)
	b.bounded(0, p.Budget)
	b.creditFee()
	b.AddOp(OP_SUB)
	b.bounded(0, p.Budget)
	b.rollingNumber(-1, 4, p.Budget)
	b.AddOp(OP_EQUALVERIFY)
	b.rollingNumber(0, 12, int64(MaxSequence))
	b.creditFee()
	b.AddOp(OP_0NOTEQUAL).AddOp(OP_IF).AddOp(OP_1ADD).AddOp(OP_ENDIF)
	b.rollingNumber(-1, 12, int64(MaxSequence))
	b.AddOp(OP_EQUALVERIFY)
	// Remove exactly the authenticated debit from the previous history.
	b.receiptField(32, DebitSize)
	b.AddData([]byte{1}).AddOp(OP_SWAP).AddOp(OP_CAT).AddOp(OP_SHA256)
	b.receiptField(32, 8)
	b.unsigned(8, int64(MaxSequence-1))
	b.historyRoot()
	b.rollingRoot(0)
	b.AddOp(OP_EQUALVERIFY)
	empty := EmptyRoots()[0]
	b.AddData(empty[:])
	b.receiptField(32, 8)
	b.unsigned(8, int64(MaxSequence-1))
	b.historyRoot()
	b.creditFee()
	b.AddOp(OP_0NOTEQUAL).AddOp(OP_IF)
	// The removal root is the insertion's authenticated intermediate root.
	b.AddOp(OP_TOALTSTACK)
	b.dropHistoryProof()
	b.AddData(empty[:])
	b.rollingNumber(0, 12, int64(MaxSequence-1))
	b.historyRoot()
	b.AddOp(OP_FROMALTSTACK).AddOp(OP_EQUALVERIFY)
	b.AddData([]byte{1})
	b.rollingNumber(0, 12, int64(MaxSequence-1))
	b.AddInt64(8).AddOp(OP_NUM2BIN).AddOp(OP_CAT)
	b.creditFee()
	b.AddInt64(8).AddOp(OP_NUM2BIN).AddOp(OP_CAT)
	b.AddInt64(0).AddOp(OP_INSPECTINPUTOUTPOINT)
	b.eq(0)
	b.AddData([]byte{0, 0, 0, 0}).AddOp(OP_CAT).AddOp(OP_CAT).AddOp(OP_SHA256)
	b.rollingNumber(0, 12, int64(MaxSequence-1))
	b.historyRoot()
	b.rollingRoot(-1)
	b.AddOp(OP_EQUALVERIFY)
	b.dropHistoryProof()
	b.AddOp(OP_ELSE)
	b.rollingRoot(-1)
	b.AddOp(OP_EQUALVERIFY)
	b.dropHistoryProof()
	b.AddOp(OP_ENDIF).AddOp(OP_FROMALTSTACK).AddOp(OP_DROP).
		AddOp(OP_DEPTH)
	b.eq(0)
	b.AddOp(OP_TRUE)
	return b.Script()
}
