package vault

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"strings"
	"testing"

	"github.com/arkade-os/emulator/pkg/arkade"
	"github.com/btcsuite/btcd/btcec/v2"
	"github.com/btcsuite/btcd/btcutil/psbt"
	"github.com/btcsuite/btcd/wire"
)

// Fixture PSBTs from arkade-wallet-vault src/lib/vault/v5 (commit d299463).
// Regenerated by building the savings-hardware initiate and phone clawback
// PSBTs from V5_FIXTURE_FAMILY.
const (
	v5VaultBaseHex = "03499fdf9e895e719cfd64e67f07d38e3226aa7b63678949e6e49b241a60e823e4"
	v5InitiatePSBT = "70736274ff0100fd0e01020000000111111111111111111111111111111111111111111111111111111111111111110000000000fdffffff036cc0000000000000225120ded0e95d73e04de7a7e2c596f2b879a41c3c465f1fad999208b63d1baa0feafff0000000000000000451024e7300000000000000009a6a4c9741524b0191010100008bd25288d30088d4518800cb05fdffffff0088d5538800d1518820ded0e95d73e04de7a7e2c596f2b879a41c3c465f1fad999208b63d1baa0feaff8800cf024a01a26951d15188024e738851cf02f0008852cf008851f469096a4c9741524b0191017c7ea852d14f888800c900cf9451cf947600a26976028813a16976d6028f0193539354965a95a16975510100000000000001012b50c3000000000000225120164e79b6ad2cc9a5ec31d25c3c9f3e6dc37e868abd8ded6934bf449dc0a8943c6215c1ede3b7632d8e9bf051579ed416c0f54cded733c378f4d863434ae18070a6d94b43665c74e00c0f02a22f0f3a86fbfac9a58ffdcd6d9b860936a1ef35c6890aeb4f51d456430841ed71df9d265e1e5fe58dae300413186c77a0dfb5fedf44d8836720e493dbf1c10d80f3581e4904930b1404cc6c13900ee0758474fa94abe8c4cd13ad203c4c86f3bdd5dc0bbf2add2fb180901320b1ff09682ff3bc90f3d64916d1e4b4ad20e93dcbebdc9221454af6c767c42958486f92b7076fbdb5b655f7028835374ef2acc0011720ede3b7632d8e9bf051579ed416c0f54cded733c378f4d863434ae18070a6d94b00000000"
	v5ClawbackPSBT = "70736274ff0100fd0e01020000000111111111111111111111111111111111111111111111111111111111111111110000000000fdffffff036cc0000000000000225120d5f2b62c2d6d9f04052467a7b58efe6a4460715f7d5aad0b03bfc84885ae1877f0000000000000000451024e7300000000000000009a6a4c9741524b0191010100008bd25288d30088d4518800cb05fdffffff0088d5538800d1518820d5f2b62c2d6d9f04052467a7b58efe6a4460715f7d5aad0b03bfc84885ae18778800cf024a01a26951d15188024e738851cf02f0008852cf008851f469096a4c9741524b0191017c7ea852d14f888800c900cf9451cf947600a26976028813a16976d6028f0193539354965a95a16975510100000000000001012b50c3000000000000225120ded0e95d73e04de7a7e2c596f2b879a41c3c465f1fad999208b63d1baa0feaff6215c0b08e8277eaabb5a3321170e4232db4716f27180e3646c50fd3c3e411d3b341e4402b1dbd108d9a57536e6c4de708535419951df9e52194bd15556b11912910195805f319c612d79ece4cea63b6b093893079116ecf689fff74d714c41439cf346720f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9ad20b191284b51f206eb07efff2a820ab024ff1631ddfd0a4b0d98d20014e679ff53ad2005e7f8609d59f588ec32d1cbf9b830e9e99604e2dfb19f130419fc9f3d6cec27acc0011720b08e8277eaabb5a3321170e4232db4716f27180e3646c50fd3c3e411d3b341e400000000"
)

func TestV5TransitionScriptsExecuteOnEmulator(t *testing.T) {
	t.Parallel()
	base := mustPub(t, v5VaultBaseHex)
	for _, name := range []string{"initiate", "clawback"} {
		raw := v5InitiatePSBT
		if name == "clawback" {
			raw = v5ClawbackPSBT
		}
		ptx := mustPSBT(t, raw)
		if err := executeV5Transition(ptx, base); err != nil {
			t.Fatalf("%s: honest transition rejected: %v", name, err)
		}
	}
}

func TestV5TransitionScriptsRejectMutations(t *testing.T) {
	t.Parallel()
	base := mustPub(t, v5VaultBaseHex)
	ptx := mustPSBT(t, v5InitiatePSBT)
	if err := executeV5Transition(ptx, base); err != nil {
		t.Fatalf("honest initiate: %v", err)
	}

	wrongDest := cloneV5PSBT(t, ptx)
	wrongDest.UnsignedTx.TxOut[0].PkScript[10] ^= 0x01
	if err := executeV5Transition(wrongDest, base); err == nil {
		t.Fatal("accepted a mutated destination")
	}

	wrongP2A := cloneV5PSBT(t, ptx)
	wrongP2A.UnsignedTx.TxOut[1].Value = 0
	if err := executeV5Transition(wrongP2A, base); err == nil {
		t.Fatal("accepted a zero-value P2A")
	}

	finalSeq := cloneV5PSBT(t, ptx)
	finalSeq.UnsignedTx.TxIn[0].Sequence = wire.MaxTxInSequenceNum
	if err := executeV5Transition(finalSeq, base); err == nil {
		t.Fatal("accepted a final sequence")
	}

	droppedPacket := cloneV5PSBT(t, ptx)
	droppedPacket.UnsignedTx.TxOut = droppedPacket.UnsignedTx.TxOut[:2]
	if err := executeV5Transition(droppedPacket, base); err == nil {
		t.Fatal("accepted a packetless transition")
	}
}

func executeV5Transition(ptx *psbt.Packet, base *btcec.PublicKey) error {
	packet, err := arkade.FindEmulatorPacket(ptx.UnsignedTx)
	if err != nil {
		return err
	}
	if len(packet) != 1 {
		return fmt.Errorf("expected one emulator entry")
	}
	script, err := arkade.ReadArkadeScript(ptx, base, packet[0])
	if err != nil {
		return err
	}
	prev := ptx.Inputs[0].WitnessUtxo
	fetcher := NewPrevFetcher(ptx.UnsignedTx.TxIn[0].PreviousOutPoint, prev)
	return script.Execute(ptx.UnsignedTx, fetcher, 0)
}

func mustPSBT(t *testing.T, h string) *psbt.Packet {
	t.Helper()
	raw, err := hex.DecodeString(h)
	if err != nil {
		t.Fatal(err)
	}
	ptx, err := psbt.NewFromRawBytes(bytes.NewReader(raw), false)
	if err != nil {
		t.Fatal(err)
	}
	return ptx
}

func mustPub(t *testing.T, h string) *btcec.PublicKey {
	t.Helper()
	raw, err := hex.DecodeString(h)
	if err != nil {
		t.Fatal(err)
	}
	pub, err := btcec.ParsePubKey(raw)
	if err != nil {
		t.Fatal(err)
	}
	return pub
}

func cloneV5PSBT(t *testing.T, src *psbt.Packet) *psbt.Packet {
	t.Helper()
	raw, err := src.B64Encode()
	if err != nil {
		t.Fatal(err)
	}
	ptx, err := psbt.NewFromRawBytes(strings.NewReader(raw), true)
	if err != nil {
		t.Fatal(err)
	}
	return ptx
}
